<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookList [
<!ELEMENT bookList (book+)>
<!ELEMENT book     (name,price)>
<!ELEMENT name     (#PCDATA)>
<!ELEMENT price    (#PCDATA)>
]>

<?xml-stylesheet type="text/xml" href="a.xsl" ?>

<bookList>
	<book>
		<name>Java教科書</name>
		
		<?browzer break ?>
		
		<price>2800</price>
	</book>
	<book>
		<name>XML教科書</name>
		<price>1500</price>
	</book>
</bookList>
