<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookList [
<!ELEMENT bookList (book+)>
<!ELEMENT book     (name,price)>
<!ELEMENT name     (#PCDATA)>
<!ELEMENT price    (#PCDATA)>
]>

<bookList>
	<book>
		<name>Java教科書</name>
		<price>2800</price>
	</book>
	
	<!-- 6月新刊です -->
	<book>
		<name>XML教科書</name>
		<!-- 消費税込みの金額です -->
		<price>1500</price>
	</book>
</bookList>
